[package]
name = "localview"
version = "0.2.0-beta.4"
license = "MIT"
repository = "https://github.com/theradengai/localview"
description = "A lightweight local-first document workspace"
authors = ["theradengai"]
edition = "2021"

[lib]
name = "localview_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
url = "2"
percent-encoding = "2"
notify-debouncer-full = "0.7"
calamine = { version = "0.36.0", features = ["dates"] }
csv = "1"
zip = "8.6"

[target.'cfg(unix)'.dependencies]
rustix = { version = "=1.1.4", features = ["fs"] }

[target.'cfg(target_os = "macos")'.dependencies]
base64 = "0.22"
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
objc2-quick-look-ui = "0.3.2"
objc2-quick-look-thumbnailing = "0.3.2"
